language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
install:
  - yarn
before_script:
  - export CI=false
script:
  - yarn build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./build/
  domain: https://burfield-stocks.surge.sh
